version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/Phoenix.Web"
    schedule:
      interval: "daily"
      time: "14:00"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
